version:  0.0
os: linux
files:
  - source: /
    destination:  /home/pi/pi-rfid
permissions:
  - object: /
    pattern: "**"
    owner: pi
    group: pi
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout:  300
      runas:  pi
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout:  300
      runas:  pi
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout:  300
      runas:  pi