version:  0.0
os: linux
files:
  - source: /
    destination:  /home/pi/pi-rfid
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout:  300
      runas:  pi
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout:  300
      runas:  pi
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout:  300
      runas:  pi
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout:  300
      runas:  pi